name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the server Docker image
      run: docker build . --file ./frps/Dockerfile --tag frps:$(date +%s)
    - name: Build the client Docker image
      run: docker build . --file ./frpc/Dockerfile --tag frpc:$(date +%s)
